name: Deploy to LocalStack with CDKTF and Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy-localstack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install -g cdktf-cli

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start LocalStack with Docker Compose
        run: docker-compose up -d

      - name: Wait for LocalStack to be ready
        run: |
          echo "⌛ Esperando que LocalStack esté listo..."
          for i in {1..30}; do
            curl -s http://localhost:4566/_localstack/health | grep "\"lambda\": \"running\"" && break
            sleep 5
          done
          echo "✅ LocalStack está listo."

      - name: Set environment for CDKTF
        run: |
          echo "ACCOUNT=000000000000" >> .env
          echo "REGION=us-east-1" >> .env
          echo "DYNAMODB_ENDPOINT=http://localhost:4566" >> .env
          echo "SNS_ENDPOINT=http://localhost:4566" >> .env
          echo "S3_ENDPOINT=http://localhost:4566" >> .env
          echo "SES_ENDPOINT=http://localhost:4566" >> .env
          echo "EMAIL_FROM=no-reply@demo.com" >> .env

      - name: Build project
        run: npm run build

      - name: CDKTF Synth
        run: npm run synth

      - name: CDKTF Deploy
        run: cdktf deploy --auto-approve

      - name: List resources (Lambda, SQS, SNS)
        run: |
          docker ps
          docker exec localstack_main awslocal lambda list-functions
          docker exec localstack_main awslocal sqs list-queues
          docker exec localstack_main awslocal sns list-topics
          docker exec localstack_main awslocal s3 ls
          docker exec localstack_main awslocal dynamodb list-tables

      - name: CDKTF Destroy
        run: cdktf destroy --auto-approve

      - name: Stop LocalStack
        run: docker-compose down
