name: Deploy to LocalStack with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  localstack-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install -g cdktf-cli

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start LocalStack using Docker Compose
        run: docker-compose up -d
        timeout-minutes: 3

      - name: Wait for LocalStack to be ready
        run: |
          until curl -s http://localhost:4566/_localstack/health | grep "\"lambda\": \"running\""; do
            echo "⏳ Esperando que LocalStack esté listo..."
            sleep 5
          done
          echo "✅ LocalStack está listo."

      - name: Set .env for CDKTF
        run: |
          echo "ACCOUNT=000000000000" >> .env
          echo "REGION=us-east-1" >> .env
          echo "DYNAMODB_ENDPOINT=http://localhost:4566" >> .env
          echo "SNS_ENDPOINT=http://localhost:4566" >> .env
          echo "S3_ENDPOINT=http://localhost:4566" >> .env
          echo "SES_ENDPOINT=http://localhost:4566" >> .env
          echo "EMAIL_FROM=no-reply@demo.com" >> .env

      - name: Compile CDKTF
        run: npm run build

      - name: Synthesize Terraform
        run: npm run synth

      - name: Deploy to LocalStack
        run: cdktf deploy --auto-approve --no-color --verbose

      - name: List Lambda functions
        run: |
          docker exec localstack_main awslocal lambda list-functions

      - name: Stop LocalStack
        if: always()
        run: docker-compose down